name: Python package

on: [push]

jobs:
    build-linux:

        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.7"]

        steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}
        - uses: conda-incubator/setup-miniconda@v2
          with:
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
        - run: |
            echo $CONDA/bin >> $GITHUB_PATH
        - name: install openmm
          run: |
            conda activate base
            conda install -c conda-forge openmm
        - name: which pip python
          run: |
            which pip
            which python
        - name: Install dependancies
          run: |  
            python -m pip install --upgrade pip
            python -m pip install nose-cov pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Test with pytest
          run: |
            nosetests
        