name: Python package

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          python-version: ["3.11"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        run: conda info
      - name: install openmm
        run: |
          conda install -c conda-forge openmm
          conda install -c conda-forge libstdcxx-ng
      - name: Install dependancies
        run: |  
          pip install coverage pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          coverage run -m pytest && coverage report -m
      - name: build package
        run: |
          pip install --upgrade build
          python -m build
          pip install -e .
          VCM -h
        